### ISSUE TITLE
[iOS]anims中的对象如果锚点不居中,动画位置会不对

### ISSUE THREAD

**Issue by hellerchen** [hardman/FlashAnimationToMobile#2]
非常感谢作者你这个开源项目.
我这里使用出现一些问题,anims中的对象如果锚点不居中,动画位置会不对,这个有什么解决办法不?

**Comment by hardman** [comment]
原件锚点是不能变的。导出脚本中没有导出锚点。所以默认认为锚点居中。所以制作动画时尽量令锚点居中。
我这边也遇到过美术人员制作原件时，某个锚点没有居中导致显示问题。一般都是让美术来改的。事实上对于美术人员锚点居中不居中都能做出同样的效果。

如果非要这样做，只能修改脚本，修改程序，令其支持任意锚点。

**Comment by hellerchen** [comment]
修改脚本只会更复杂。相对来说修改美术文件是容易的。
1. 首先在脚本中，取出原件的锚点（现在的脚本只取了position,scale,rotate,....具体看脚本）。
2. 如果使用了flabin，记得修改python脚本。
3. 然后修改程序，程序解析的部分加上表示锚点的变量。
4. 然后在绘制图片的时候，根据锚点和位置，计算正确的图片位置。

@hardman 非常感谢你的回复
嗯,是可以让美术人员来修改这个,其实我会提这个,是因为动画已经制作完成,让他们修改工作量有点大,而且锚点这个问题在他们设计的过程中出现的概率也非常高,所以想问问有什么好的解决办法.
PS:你说的修改脚本,请问关键字是什么?我可以自己去修改脚本看看

**Comment by captain-black** [comment]
@hellerchen 你的问题解决了吗? 我也面对同样问题
