### ISSUE TITLE
貌似我的测试机5c上动画跑步起来

### ISSUE THREAD

**Issue by ws1227** [hardman/FlashAnimationToMobile#4]

**Comment by hardman** [comment]
不会吧。
系统是多少？
跑起来是什么效果呢？

**Comment by ws1227** [comment]
系统是10.0.2 运行动画会卡死在第一帧

在 2016-11-02 22:07:51，"hard_man" notifications@github.com 写道：

不会吧。
系统是多少？
跑起来是什么效果呢？

**Comment by ws1227** [comment]
现在5c测试已经很流畅了👍
