### ISSUE TITLE
动画位置不对

### ISSUE THREAD

**Issue by captain-black** [hardman/FlashAnimationToMobile#6]
![wechatimg20](https://cloud.githubusercontent.com/assets/1026515/21451213/4cdd2864-c938-11e6-9946-ca82bd76e00f.jpeg)

[test_apple(1).fla.zip](https://github.com/hardman/FlashAnimationToMobile/files/670557/test_apple.1.fla.zip)
![simulator screen shot 2016 12 23 5 53 12](https://cloud.githubusercontent.com/assets/1026515/21451267/b4aedc62-c938-11e6-9ca7-4d99df91c0f7.png)
设计给的动画, 大概是这样.
我在iOS上居中显示, 但是实际上动画偏移了.
设计说按足文档指示来做的了, 而我又不懂flash...能不能帮看看哪里出问题了? @hardman

**Comment by hardman** [comment]
左上角的那个十字表示动画中心。所以flash中需要向左和上移动。

**Comment by hardman** [comment]
不好意思说错了，左上角的十字表示手机屏幕中心

**Comment by captain-black** [comment]
好的, 感谢
